project:
  type: website
  output-dir: docs/
  resources: maps/

website:
  title: "Emergência RS"
  page-navigation: true
  back-to-top-navigation: true
  google-analytics: "G-2M7VLSRDCB"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Início
  page-footer:
    background: light
    left: "![](images/logo_fiocruz.png){width=30%} ![](images/logo_icict_150.png){width=30%}"
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

